### ISSUE TITLE
Add support for external project dependencies

### ISSUE THREAD

**Issue by federicobond** [meuspedidos/codeclimate-pylint#10]
I am willing to contribute a patch to add support for this.

What is the general approach to that in Code Climate plugins?

**Comment by caiofbpa** [comment]
Hey @federicobond, thanks for your interest in contributing!

Unfortunately I think this is not possible. According to [CodeClimate Engine Spec](https://github.com/codeclimate/spec/blob/master/SPEC.md#security-restrictions):

> Engines run with no network access (--net=none in Docker). They must not rely on making any external network calls.

So in order to add external project dependencies, one would need to rebuild the engine with its own dependencies, which isn't very viable.

I'm open to other alternatives though!

**Comment by federicobond** [comment]
Hmm... that limits the usefulness of Pylint quite a bit for us. Is Meus Pedidos doing anything special to work around that? Do you vendor your dependencies first?

**Comment by caiofbpa** [comment]
Indeed it limits! Maybe this explains why no one else had ported Pylint to be a CodeClimate engine before.

We're planning on using Pylint to help migrate our codebase from Python 2 to 3, so we won't need many external dependencies or plugins. It's a pretty small use case compared to all Pylint has to offer, but it's enough for us.

**Comment by federicobond** [comment]
That makes sense. Thank you for taking the time to answer.

**Comment by caiofbpa** [comment]
I'll close this for now, if you have any other ideas about this feel free to comment again 😄
